// top of the history_past stack is the most recently displayed result
var history_past = []
var redo_stack = []

var suitStarts = ["Weapons Building","Crouched behind a Truck","Red Carpet","Palace Garden","Pile-Driver Barge","Attic","Undercover at IAGO Auction","Main Square","ICA Safe House","Harbor","Sapienza Ruins","Main Square Tower","Church Morgue","City Gates","Promenade","Bazaar Entrance","Lamp Store Rooftop","School Alley","Consulate Parking Garage","Consulate Plaza","Riverside Landing","Agent 47's Suite","West Bridge","Old Orchard","Southern Farm Perimeter","Water Tower","Infiltrating Along the Mountain Path","Hotel Front Terrace","Portico","Infiltrating below the Helipad","Boat","Office","Beach","Event Entrance","Dolphin Fountain","Marina","Stands","Village Bus Stop","Village Hostel","Shaman's Hut","Village Bar","Main Street","Train","Skywalk","Taxi","Chawls","Whittleton Creek","Chapel","Keep"];
var disguiseExits = ["Ambulance|(Medic Only)","Nest|(Secret)","Pale Rider|(Secret)","Trash Truck|(Garbage Man Only)","Swan Dive|(Secret)"];
var koExits = ["Pink Car|(Needs Key)","Rico's Supercar|(Needs Key)","Local's Car|(Needs Key)","Roadwork Gate|(Needs Key)"];
var proOnly = ["training","test","movie","election","handoff","construction","cult","spread"];

var mechList = ["Instinct|Turn off Instinct in the game's Options menu under Gameplay.",
				"Mini Map|Turn off the Mini Map in the game's Options menu under Gameplay.",
				"Attention Alert|Turn off Attention Alert in the game's Options menu under Gameplay.",
				"NPC Icons|Turn off NPC Icons in the game's Options menu under Gameplay.",
				"Weapon HUD|Turn off Weapon HUD in the game's Options menu under Gameplay.",
				"Picture In Picture|Turn off Picture In Picture in the game's Options menu under Gameplay.",
				"Limited Vision Area|Turn off the Limited Vision Area in the game's Options menu under Gameplay.",
				"No Agility|Do not vault, hang, scale, or climb down.",
				"No Crouching|Do not crouch."];
var timeList = [5,7,10,12,15,20,25,30,40,50,60];
var ratingList = ["Hunted Slayer|Complete the roulette and achieve at least a one star rating.",
				  "Wanted Murderer|Complete the roulette and achieve at least a two star rating.",
				  "Missing Killer|Complete the roulette and achieve at least a three star rating.",
				  "Quiet Hitman|Complete the roulette and achieve at least a four star rating.",
				  "Silent Assassin|Complete the roulette and achieve a five star rating."];
var difficultyList = ["Casual","Professional","Master"];

var generic = {
	kills: ["Any Firearm","Any Small Melee Weapon","Any Large Melee Weapon","Accident","Explosion","Lethal Poison","Unarmed"],
	firearms: ["Pistol","Sniper Rifle","Explosive (Weapon)","Assault Rifle","SMG","Shotgun","Pistol Elimination"],
	accidents: ["Drowning|Accident","Falling Object|Accident","Fall|Accident","Fire|Accident","Electricity|Accident","Explosion|Accident"],
};

var fftfailsafe = ["Sniper Rifle","SMG","Any Small Melee Weapon","Any Large Melee Weapon","Lethal Poison","Fire|Accident","Electricity|Accident","Explosion|Accident"];
var fftfailsafeContract = ["Sniper Rifle","SMG","Shotgun","Assault Rifle","Any Small Melee Weapon","Any Large Melee Weapon","Lethal Poison","Fire|Accident","Electricity|Accident"];
var fft = {
	missionTitle: "Freeform Training",
	missionLocation: "ICA Facility",
	missionCode: "training",
	melee: ["Fiber Wire","Fiber Wire","Fiber Wire","Fiber Wire","Fiber Wire"],
	targetList: ["Kalvin Ritter"],
	contractTargets: ["Kalvin Ritter|Currently mingling with guests throughout the yacht. Waiting for Terry Norfolk.",
	"Terry Norfolk|Last seen standing just outside the yacht. (Level 0)",
	"Thomas Cross|Having a conversation on a couch near the bar. (Level 1)",
	"Isabella Caruso|Talking with someone on the upper deck. (Level 2)",
	"Calista Hoff|Standing near the bar on the upper deck. (Level 2)",
	"Ronnie Aguilar|Bodyguard to Kalvin Ritter, host of the party.",
	"Olivia D. Trent|Last seen talking with a friend before touring the yacht. (Level 1)",
	"James Potts|Cooking in the kitchen."],
	entry: ["Weapons Building"],
	exit: ["Button by the Red Car","Button by the Speedboat","Button by the Helicopter"],
	eexit: ["Button by the Red Car","Button by the Speedboat","Button by the Helicopter"],
	disguises: ["Training Gear","Mechanic","Yacht Crew","Yacht Security","Bodyguard","Terry Norfolk"],
	wild: ["Loading Bay Entrance|Only enter the yacht through the loading bay.",
	"Sneaking Mission|You must enter the yacht in your Training Gear before killing any targets.",
	"Crocodile Hunter|Pop the inflatable crocodile by the pool.",
	"The Private Meeting|Disguise yourself as Norfolk and meet with Ritter in private."],
	contractWild: ["Loading Bay Entrance|Only enter the yacht through the loading bay.",
	"Sneaking Mission|You must enter the yacht in your Training Gear before killing any targets.",
	"Crocodile Hunter|Pop the inflatable crocodile by the pool."],
};

var icafailsafe = ["Sniper Rifle","SMG","Shotgun","Any Small Melee Weapon","Any Large Melee Weapon","Explosion","Lethal Poison","Explosive (Weapon)","Fire|Accident","Electricity|Accident","Explosion|Accident"];
var ica = {
	missionTitle: "The Final Test",
	missionLocation: "ICA Facility",
	missionCode: "test",
	melee: ["Fiber Wire","Fiber Wire","Fiber Wire","Fiber Wire","Fiber Wire"],
	targetList: ["Jasper Knight"],
	contractTargets: ["Jasper Knight|Wandering around the hanger, waiting for KGB contact.",
	"Cilas Netzke|The sole KGB Officer on the premises.",
	"Kelly R. Edwards|Security manning the front desk. (Level 0)",
	"Rodion Evdokimov|Tasked with guarding the west stairway. (Level 1)",
	"Evan Gomez|Cooking in the kitchen.",
	"Moses Butusov|Tasked with guarding the commander's office.",
	"David Hoosier|A Mechanic working on the fighter jet.",
	"Christopher May|Airport security working the front gate.",
	"Luke Yuriev|Last seen smoking on the hanger roof."],
	entry: ["Crouched behind a Truck"],
	exit: ["Button by the Car"],
	eexit: ["Button by the Car"],
	disguises: ["Training Gear","Airplane Mechanic","Airfield Security","Soviet Soldier","KGB Officer"],
	wild: ["Total Elimination|Kill everyone in the level only after taking out Jasper Knight.<br /><br />If killing non-targets is not permitted, then only pacify.",
	"Direct Approach|You can only enter the hanger by jumping the barricade.",
	"Misdirection|You can only enter the hanger by jumping the west side of the fence.",
	"Nobody In Sight|You can only enter the hanger by jumping the east side of the fence.",
	"Five O'Clock|Acquire the Bottle of Vodka",
	"To Fallen Comrades|Solve the chess puzzle.",
	"A Slide Show|Collect the Projector Slides.",
	"Safety First|Sabotage the ejector seat."],
	contractWild: ["Total Elimination|Kill everyone in the level only after taking out the target(s).<br /><br />If killing non-targets is not permitted, then only pacify.",
	"Direct Approach|You can only enter the hanger by jumping the barricade.",
	"Five O'Clock|Acquire the Bottle of Vodka",
	"To Fallen Comrades|Solve the chess puzzle.",
	"A Slide Show|Collect the Projector Slides.",
	"Safety First|Sabotage the ejector seat."],
};

var showstopper = {
	missionTitle: "The Showstopper",
	missionLocation: "Paris",
	missionCode: "fashion",
	melee: ["Screwdriver|Melee","Screwdriver|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Fiber Wire","Fire Axe|Melee","Fire Axe|Thrown Weapon","Battle Axe|Melee","Battle Axe|Thrown Weapon","Saber|Melee","Saber|Thrown Weapon","Hatchet|Melee","Hatchet|Thrown Weapon"],
	targetList: ["Viktor Novikov","Dalia Margolis"],
	contractTargets: ["Viktor Novikov|Overseeing the fashion show. About to head downstairs and address the crowd.",
	"Dalia Margolis|Overseeing the IAGO auction on the top floor of the palace.",
	"Sebastian Sato|Lead fashion designer for the show. In the makeup and clothing area.",
	"Helmut Kruger|Fashion model and spy for Dalia. Last seen taking photos near the helicopter.",
	"Max Decker|Bribed FSB agent waiting just outside the bar lounge to meet with Novikov.",
	"Sheikh Salman al-Ghazali|Guest of honor at the IAGO auction with his own quarters in the palace. (Level 2)",
	"Lindsey La Coeur|Fashion blogger covering the show. Last seen reporting out front.",
	"Jay Smart|Camera operator for Lindsey La Coeur. Last seen filming out front.",
	"Lana Caprice|Blogger for a webzine, hoping to interview Novikov. Last seen near the empty cafe. (Level 1)",
	"Valerie St. Clair|Writer hoping to expose Novikov. Last seen speaking with her assistant near the bar lounge. (Level 1)",
	"Liza McKenzie|Last seen speaking with her boss, Valerie St. Clair, in a hallway near the bar lounge. (Level 1)",
	"Hailey Brennan|Dalia's secretary and undercover spy. Nearby the auction laptop.",
	"Kurt Donovan|Viktor's bodyguard overseeing evacuation protocol via.",
	"Sophus Fatale|Dalia's personal assistant and manager. Last seen with her near the auction.",
	"Martha Herris|IAGO spy standing nearby the top floor auction.",
	"Tren Po|Prince of a third-world country. In a hallway just outside the IAGO auction.",
	"Sir Humphrey Titus Rutherford|British weapon manufacturer drinking champagne on the top floor patio.",
	"Mabaya Mzabumi|Representative of terror organization Crystal Dawn currently on the top floor patio."],
	entry: ["Red Carpet","Palace Garden","Pile-Driver Barge","Attic","Undercover in Kitchen","Undercover in Locker Room","Undercover at IAGO Auction","Undercover in AV Center","Undercover in Dressing Area"],
	exit: ["Front Gates (Main)","Front Gates (Side)","Front Gate (Parking Lot)","Basement Catacombs","Helicopter","Baron Larin's Speedboat|(Needs Key)"],
	eexit: ["Front Gates (Main)","Front Gates (Side)","Front Gate (Parking Lot)","Basement Catacombs","Helicopter","Baron Larin's Speedboat|(Needs Key)"],
	disguises: ["Any Suit","Auction Staff","Chef","CICADA Bodyguard","Tech Crew","Palace Staff","Security Guard","Stylist","Helmut Kruger","Sheikh","Vampire Magician"],
	wild: ["Take (Out) The Money|Eliminate Viktor Novikov before Dalia Margolis.",
	"Agent Versus Spy|Eliminate Dalia Margolis before Viktor Novikov.",
	"Piano Forty Seven|Knock someone out with the piano.",
	"Bull in a China Shop|Break the asian antique vase in the first floor storage room.",
	"Bare Knuckle Boxer|Mix a Bare Knuckle Boxer cocktail.",
	"Fifteen Seconds of Fame|Take to the catwalk as Helmut Kruger.",
	"Salut Too Soon|Trigger the fireworks ahead of schedule by finding the remote.",
	"A Rare Scoop|Find a camera lens for blogger Lana Caprice so she can meet with Novikov. Do not eliminate Novikov before completing this.",
	"Enter the IAGO Auction|Join the auction with an invitation or dressed as the Sheikh.",
	"A Quick Break|Hack Dalia's computer and sabotage the auction."],
	contractWild: ["Piano Forty Seven|Knock someone out with the piano.",
	"Bull in a China Shop|Break the asian antique vase in the first floor storage room.",
	"Bare Knuckle Boxer|Mix a Bare Knuckle Boxer cocktail.",
	"Fifteen Seconds of Fame|Take to the catwalk as Helmut Kruger.",
	"Salut Too Soon|Trigger the fireworks ahead of schedule by finding the remote.",
	"A Rare Scoop|Find a camera lens for blogger Lana Caprice so she can meet with Novikov.",
	"Enter the IAGO Auction|Join the auction with an invitation or dressed as the Sheikh.",
	"A Quick Break|Hack Dalia's computer and sabotage the auction."],
};

var wot = {
	missionTitle: "World of Tomorrow",
	missionLocation: "Sapienza",
	missionCode: "virus",
	melee: ["Battle Axe|Melee","Battle Axe|Thrown Weapon","Old Axe|Melee","Old Axe|Thrown Weapon","Katana|Melee","Katana|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon", "Saber|Melee","Saber|Thrown Weapon","Amputation Knife|Melee","Amputation Knife|Thrown Weapon","Circumcision Knife|Melee","Circumcision Knife|Thrown Weapon","Combat Knife|Melee","Combat Knife|Thrown Weapon","Hatchet|Melee","Hatchet|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fiber Wire"],
	targetList: ["Silvio Caruso","Francesca De Santis"],
	contractTargets: ["Silvio Caruso|Troubled genius. Currently practicing his golf swing, awaiting a myriad of appointments.",
	"Francesca De Santis|Lab head. Currently rummaging through Caruso's things.",
	"Terenzio Endrizzi|Caruso's butler, standing at the front door awaiting visitors.",
	"Roberto Vargas|Ladies man and Caruso's personal golf coach, currently helping him improve his swing.",
	"Chef Marcello Ray|Caruso's Head Chef, working on a spaghetti bolognese recipe in the mansion's separate kitchen.",
	"Dr. Oscar Lafayette|A psychiatrist hired to work through Caruso's issues. Currently at the ice cream shop before heading over.",
	"Torres Piombo|Bohemian who lives on the top floor above the Gelateria Bella (ice cream shop).",
	"Sal Falcone|Private investigator hired by Caruso. Planning to meet with De Santis. Napping on a bench. (Level 2)",
	"Viana Buccho|Ether scientist mourning an accidentally contaminated co-worker. Holds the Biolab Laptop Dongle.",
	"Fabio Pavione|Working at the front office in the morgue.",
	"Mario Saltatore|A plumber in a red uniform working in the sewers under the church.",
	"Luigi Saltatore|A plumber in a green uniform working in Caruso's Mansion Basement.",
	"Jack Please|Waiter for the Gelateria Bella (ice cream shop).",
	"Padre Francesco|The local priest, obviously working in the church.",
	"Craig “Rocco” McVeigh|Caruso's newly hired cook that would rather be playing video games in his apartment."],
	entry: ["Main Square","ICA Safe House","Harbor","Sapienza Ruins","Main Square Tower","Church Morgue","Undercover in Mansion Kitchen","Undercover in Field Lab","Undercover in Mansion Garden","Undercover as Security Staff"],
	exit: ["Car","Speedboat (Harbor)","Seaplane","Speedboat (Ruins)"],
	eexit: ["Car","Speedboat (Harbor)","Seaplane","Speedboat (Ruins)"],
	disguises: ["Any Suit","Biolab Security","Bodyguard","Bohemian","Butler","Church Staff","Cyclist","Delivery Man","Dr. Oscar Lafayette","Gardener","Green Plumber","Hazmat Suit","Housekeeper","Kitchen Assistant","Lab Technician","Mansion Chef","Mansion Security","Mansion Staff","Plague Doctor","Priest","Private Detective","Red Plumber","Roberto Vargas","Store Clerk","Street Performer","Waiter"],
	wild: ["Ladies First|Eliminate Francesca De Santis before Silvio Caruso or the Virus.",
	"Add Paranoia To The List|Eliminate Silvio Caruso before Francesca De Santis or the Virus.",
	"Starve A Cold|Destroy the Virus before eliminating any targets.",
	"Back Door|Only enter Villa Caruso through the biolab.",
	"A Family Affair|Find and play Silvio Caruso's family video.",
	"Safehouse Bugged|The ICA Safehouse is off limits from entering and receiving Agency pickups.<br /><br />If this is your starting location, disregard it and choose your own.",
	"Agent 427|Retrieve a cannabis joint.",
	"Share One With Diana|Retrieve two cannabis joints.",
	"Catharsis|Witness Caruso's therapy session. Disguising yourself as the Psychiatrist is optional.",
	"First Day on the Job|Attempt to cook Isabella Caruso's spaghetti bolognese and ring the dinner bell.",
	"The Good Son|Place flowers on Isabella Caruso's Grave while disguised as a delivery man.",
	"Green Thumb|Find all 6 flower bouquets hidden around Sapienza.",
	"For Whom the Bell Tolls|Drop the church bell.",
	"Remote Detonation|Retrieve the dongle and destroy the virus via the laptop.",
	"Kill Shot|Shoot the virus with a ballistic weapon to destroy it.",
	"Precision Cave In|Destroy the virus by dropping a stalactite on it.",
	"Leave No Trace|Collect the Virus Prototype.<br /><br />You are permitted to use it as a kill method."],
	contractWild: ["A Family Affair|Find and play Silvio Caruso's family video.",
	"Safehouse Bugged|The ICA Safehouse is off limits from entering and receiving Agency pickups.<br /><br />If this is your starting location, disregard it and choose your own.",
	"Agent 427|Retrieve a cannabis joint.",
	"Share One With Diana|Retrieve two cannabis joints.",
	"First Day on the Job|Attempt to cook Isabella Caruso's spaghetti bolognese and ring the dinner bell.",
	"The Good Son|Place flowers on Isabella Caruso's Grave while disguised as a delivery man.",
	"Green Thumb|Find all 6 flower bouquets hidden around Sapienza.",
	"For Whom the Bell Tolls|Drop the church bell.",
	"Leave No Trace|Collect the Virus Prototype.<br /><br />You are permitted to use it as a kill method."],
};

var icon = {
	missionTitle: "The Icon",
	missionLocation: "Sapienza",
	missionCode: "movie",
	melee: ["Battle Axe|Melee","Battle Axe|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon","Knife|Melee","Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fiber Wire"],
	targetList: ["Dino Bosco"],
	contractTargets: ["Dino Bosco|Difficult actor also filling the director roll. Just follow the voice...",
	"Palmiro Russo|Movie Crew member speaking to another outside the city gates.",
	"Enrico Nucci|Working the Merchandise stand next to the interview area.",
	"Sophia Wilde|Bosco's agent who set up the Q&A session.",
	"Giuseppe Monaldo|Guard in the Main Square Tower.",
	"Amaranto “Tony” Mazzi|SFX Crew member inside the pottery store.",
	"Arturo Tossi|Kitchen Assistant manning catering in the ice cream shop.",
	"Uranio Lucchese|SFX Crew member standing across from the air ramp controls."],
	entry: ["City Gates"],
	exit: ["Town Gate","Bosco's Car|(Needs Key)"],
	eexit: ["Town Gate","Bosco's Car|(Needs Key)"],
	disguises: ["Any Suit","Kitchen Assistant","Moview Crew","Security Officer","SFX Crew"],
	wild: ["Time to Meet the Fans|Interrupt the film shoot by tampering with the generator rack.",
	"Free Falling|Drop one body off the top of the Main Square Tower.",
	"Key Grip|Find all 5 keys scattered around: Town Hall Key, Shop Key, Fuel Case Key, and Bosco’s Car & Trailer Keys.",
	"Nighttime Vandal|Sabotage 6 of the 13 scooters parked nearby the set."],
	contractWild: ["Time to Meet the Fans|Interrupt the film shoot by tampering with the generator rack.",
	"Free Falling|Drop one body off the top of the Main Square Tower.",
	"Key Grip|Find all 5 keys scattered around: Town Hall Key, Shop Key, Fuel Case Key, and Bosco’s Car & Trailer Keys.",
	"Nighttime Vandal|Sabotage 6 of the 13 scooters parked nearby the set."],
};

var landslide = {
	missionTitle: "Landslide",
	missionLocation: "Sapienza",
	missionCode: "election",
	melee: ["Fiber Wire","Screwdriver|Melee","Screwdriver|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Old Axe|Melee","Old Axe|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Saber|Melee","Saber|Thrown Weapon","Folding Knife|Melee","Folding Knife|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon"],
	targetList: ["Marco Abiatti"],
	contractTargets: ["Marco Abiatti|Local Politician with ulterior motives. Roaming around the festival.",
	"Davide Battistelli|Stage crew member watching over the fireworks.",
	"Marcello Folliero|Abiatti’s Photographer, starting with a session on the beach.",
	"Alberta Arcuri|Working around the back of Abiatti's merchandise stand.",
	"Padre Francesco|The local priest in the church, trying to dodge a meeting with Abiatti.",
	"Mario Saltatore|A plumber in a red uniform working in the sewers under the church well.",
	"Luigi Saltatore|A plumber in a green uniform working in the sewers under the church well.",
	"Cristina Dionisi|Singer of Cinque Ciliegie, playing at the Abiatti sponsored country festival.",
	"Felix Merkl|Guitarist of Cinque Ciliegie, playing at the Abiatti sponsored country festival.",
	"Michele Delle Marche|Keyboardist of Cinque Ciliegie, playing at the Abiatti sponsored country festival.",
	"Roberto Mulo|Abiatti's “third eye” watching over the festival from an apartment. (Level 3)",
	"Valerio Polloni|Working alone in the morgue.",
	"Renzo Forte|Current resident in the gamer apartment upstairs from the ICA Safe House.",
	"Silvestro Pugliesi|Bohemian who lives on the top floor above the Gelateria Bella (ice cream shop).",
	"Salvatore Bravuomo|Lawyer with dirt on Abiatti. Currently hiding from his goons.",
	"Silvia Morando|Salvatore Bravumo’s Secretary, currently dealing with ransackers in their offices.",
	"Dott. Docciaborsa|Brain surgeon looking to meet Abiatti at his stand soon.",
	"Professor Antonio|A journalist writing for the Repubblica newspaper. Planning on meeting Abiatti.",
	"Monia Bellini|Over-the-hill stage play writer enjoying the festival. Planning on meeting Abiatti.",
	"Mariano Palerma|Bartender at the stand alone wine bar to the south.",
	"Dario Bronzo|Baker working at the isolated bakery on the upper balcony above the festival stage."],
	entry: ["Promenade"],
	exit: ["Town Gate","Pink Car|(Needs Key)","Speedboat|(Needs Key)"],
	eexit: ["Town Gate","Pink Car|(Needs Key)","Speedboat|(Needs Key)"],
	disguises: ["Any Suit","Stage Crew","Security","Bodyguard","Photographer","Waiter","Church Staff","Priest","Gardener","Green Plumber","Red Plumber","Kitchen Assistant","Salvatore Bravuomo","Bohemian"],
	wild: ["Big Brother|Turn off Abiatti’s “Third Eye” webcam. Ensure it is not fixed.",
	"Unsafe Distance|Tamper with the fireworks, find the Remote Detonator, and Trigger the fireworks.",
	"Cheat Sheet|Reschedule Abiatti’s meeting before he meets with Father Francesco.",
	"No Absolution for the Wicked|Hear Marco Abiatti’s confession.",
	"Above the Law|Witness or “participate” in Abiatti’s meeting with Salvatore Bravuomo.",
	"Enter and Break|Retrieve Salvatore Bravuomo’s Folding Knife.",
	"Dynamic Smile|Get Abiatti’s picture by the pier.",
	"Safehouse Bugged|The ICA Safehouse is off limits from entering and receiving Agency pickups.",
	"For Whom the Bell Tolls|Drop the church bell."],
	contractWild: ["Big Brother|Turn off Abiatti’s “Third Eye” webcam. Ensure it is not fixed.",
	"Unsafe Distance|Tamper with the fireworks, find the Remote Detonator, and Trigger the fireworks.",
	"Cheat Sheet|Reschedule Abiatti’s meeting before he meets with Father Francesco.",
	"No Absolution for the Wicked|Hear Marco Abiatti’s confession.",
	"Above the Law|Witness or “participate” in Abiatti’s meeting with Salvatore Bravuomo.",
	"Enter and Break|Retrieve Salvatore Bravuomo’s Folding Knife.",
	"Dynamic Smile|Get Abiatti’s picture by the pier.",
	"Safehouse Bugged|The ICA Safehouse is off limits from entering and receiving Agency pickups.",
	"For Whom the Bell Tolls|Drop the church bell."],
};

var author = {
	missionTitle: "The Author",
	missionLocation: "Sapienza",
	missionCode: "handoff",
	melee: ["Battle Axe|Melee","Battle Axe|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon","Knife|Melee","Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fiber Wire"],
	targetList: ["Craig Black","Brother Akram"],
	contractTargets: ["Craig Black|Conflicted author. Doing book readings in the church while waiting for his meeting.",
	"Brother Akram|High ranking cult operative. In an apartment, waiting for his meeting. (Level 3)"],
	entry: ["Portico"],
	exit: ["Car","Town Gate","Speedboat"],
	eexit: ["Car","Town Gate","Speedboat"],
	disguises: ["Any Suit","Waiter","Craig Black","Brother Akram","Super Fan","Bodyguard"],
	wild: ["Two for the Price of None|Collect two bottles of Insecticide.",
	"Critic Critique|Collect Mike Vogt’s book reading invitation.",
	"Too Much Ambiance|Pollute the smoke machine being used for the promotional photoshoot.",
	"No, it's “Cheese”|Get your picture taken with Craig Black during the promotional photoshoot."],
	contractWild: ["Two for the Price of None|Collect two bottles of Insecticide.",
	"Critic Critique|Collect Mike Vogt’s book reading invitation.",
	"Too Much Ambiance|Pollute the smoke machine being used for the promotional photoshoot.",
	"No, it's “Cheese”|Get your picture taken with Craig Black during the promotional photoshoot."],
};

var agc = {
	missionTitle: "A Gilded Cage",
	missionLocation: "Marrakesh",
	missionCode: "tension",
	melee: ["Battle Axe|Melee","Battle Axe|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon","Saber|Melee","Saber|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Folding Knife|Melee","Folding Knife|Thrown Weapon","Fiber Wire"],
	targetList: ["Reza Zaydan","Claus Hugo Strandberg"],
	contractTargets: ["Reza Zaydan|Power Hungry General. Inside the school, using it as a base of operations.",
	"Claus Hugo Strandberg|Corporate sociopath. Under siege inside the Swedish consulate.",
	"Ashraf Raghib Mustafa|Member of Zaydan’s fake Crystal Dawn printing crew.",
	"Pamela Kingsley|Journalist for GNN News scheduled to interview Strandberg. Waiting just outside the protests.",
	"Jeff Baker|Freelance camera man avoiding work by enjoying the Shisha Cafe.",
	"Shahin Abdul-Barr Maalouf|The school’s old headmaster writing a book on a rooftop. (Level 3)",
	"Konny Engström|Masseur at the Swedish consulate, trying to get out of massaging Strandberg.",
	"Jawwaad Reza|Elite soldier at the locker room in the tunnel leading to the consulate.",
	"Hektor Lindberg|Consulate intern wandering Marrakesh before finding the building.",
	"Zaki Diab|Fortune teller asking for money just outside the Bazaar Entrance.",
	"Shuaib Aly|Protester with the megaphone just outside the consulate.",
	"Hilda Berg|Former security manager of the Swedish consulate, currently on the lamp store roof.",
	"Sayid Laham|Zaydan’s prisoner being held captive in the school.",
	"Alden Riauff Hansson|Currently on his third year of exile in the Swedish consulate. (Level 2)",
	"Erik Olander|The Consul of Sweden in Marrakesh. In a conference room in the consulate. (Level 2)",
	"Ellinor Westrup|Fashion model for Sanguine and former IAGO spy. In or near the Shisha Cafe."],
	entry: ["Bazaar Entrance","Undercover at the Snail Stand","Undercover on the West Bazaar Rooftop","Undercover in the Courtyard Club","Undercover in Zaydan's Compound","Lamp Store Rooftop","Undercover in the Consulate","School Alley","Consulate Parking Garage"],
	exit: ["Marketplace Gates","Bazaar Gates","Armored Vehicle|(Needs Key)","Car in the Garage|(Needs Key)"],
	eexit: ["Marketplace Gates","Bazaar Gates","Armored Vehicle|(Needs Key)","Car in the Garage|(Needs Key)"],
	disguises: ["Any Suit","Bodyguard","Cameraman","Consulate Intern","Consulate Janitor","Consulate Security","Elite Soldier","Food Vendor","Fortune Teller","Handyman","Headmaster","Local Printing Crew","Masseur","Military Officer","Soldier","Prisoner","Shopkeeper","Waiter"],
	wild: ["For The Country|Eliminate Reza Zaydan before Claus Hugo Strandberg.",
	"For The People|Eliminate Claus Hugo Strandberg before Reza Zaydan.",
	"Golden Touch|Massage Claus Hugo Strandberg.",
	"A Room With a Moose|Drop the moose statue in the Swedish Consulate Auditorium.",
	"A Sky With a Moose|Drop at least one moose statue from the sky...",
	"Training Cancelled|Trigger the APC turret in the school courtyard.",
	"Bathroom Break|Drop the broken toilet bowl in the school bathroom.",
	"Freedom|Drag Zaydan’s prisoner, Sayid Laham, outdoors.",
	"Let's Dance|Trigger the dance party at the school.",
	"Public Speaker|Get rid of the protester Sayid Laham, but do not kill them."],
	contractWild: ["Golden Touch|Massage Claus Hugo Strandberg.",
	"A Room With a Moose|Drop the moose statue in the Swedish Consulate Auditorium.",
	"A Sky With a Moose|Drop at least one moose statue from the sky...",
	"Training Cancelled|Trigger the APC turret in the school courtyard.",
	"Bathroom Break|Drop the broken toilet bowl in the school bathroom.",
	"Freedom|Drag Zaydan’s prisoner, Sayid Laham, outdoors.",
	"Let's Dance|Trigger the dance party at the school.",
	"Public Speaker|Get rid of the protester Sayid Laham, but do not kill them."],
};

var ahbos = {
	missionTitle: "A House Built on Sand",
	missionLocation: "Marrakesh",
	missionCode: "construction",
	melee: ["Battle Axe|Melee","Battle Axe|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Folding Knife|Melee","Folding Knife|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fiber Wire"],
	targetList: ["Kong Tuo-Kwang","Matthieu Mendola"],
	contractTargets: ["Kong Tuo-Kwang|Cut-throat Capitalist. Hosting a party at the Shisha Cafe.",
	"Matthieu Mendola|Industry spy betraying his employer. Lost while looking for Tuo-Kwang’s escort.",
	"Yousef Shitrit|Shopkeeper standing by the well in the southeast.",
	"Zaki Diab|Fortune teller currently working in a building to the northwest.",
	"Sebastian Krogh|Having his fortune told in a building to the northwest.",
	"Hussein Guirguis|A very sick bodyguard, vomiting near the well in the northwest.",
	"Nimr 'Arif Bahar|Landlord of an Antiques Shop. Attending the Shisha Cafe party.",
	"Ahmed Aziz|Waiter for Tuo-Kwang’s meeting spot; a lamp store rooftop.",
	"Nour Joumari|Carpet shopping body on the roof of a shop in the west."],
	entry: ["Consulate Plaza"],
	exit: ["Marketplace Gates","Bazaar Gates","Truck|(Needs Key)","Door near the Well|(Needs Crowbar)","Door by the Street|(Needs Crowbar)"],
	eexit: ["Marketplace Gates","Bazaar Gates","Truck|(Needs Key)","Door near the Well|(Needs Crowbar)","Door by the Street|(Needs Crowbar)"],
	disguises: ["Any Suit","Bodyguard","Food Vendor","Fortune Teller","Handyman","Soldier","Shopkeeper","Waiter"],
	wild: ["Climb the Corporate Ladder|Eliminate Kong Tuo-Kwang before Matthieu Mendola.",
	"Where Are You in 10 Years?|Eliminate Matthieu Mendola before Kong Tuo-Kwang.",
	"Dropping the F-bomb|Shoot down the Shisha Cafe sign.",
	"Keys to the City|Find all 6 keys scattered around: Truck Keys, Maintenance Room Key, Shisha Cafe Key, and the Antiques, Carpet, and unnamed Shop Keys.",
	"Litter Picker-Upper|Collect 10 soda cans, located in the area around the Shisha Cafe.",
	"The Future Foretold|Read Matthieu Mendola’s fortune as the fortune teller."],
	contractWild: ["Dropping the F-bomb|Shoot down the Shisha Cafe sign.",
	"Keys to the City|Find all 6 keys scattered around: Truck Keys, Maintenance Room Key, Shisha Cafe Key, and the Antiques, Carpet, and unnamed Shop Keys.",
	"Litter Picker-Upper|Collect 10 soda cans, located in the area around the Shisha Cafe.",
	"The Future Foretold|Read Matthieu Mendola’s fortune as the fortune teller."],
};

var c27 = {
	missionTitle: "Club 27",
	missionLocation: "Bangkok",
	missionCode: "birthday",
	melee: ["Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Hatchet|Melee","Hatchet|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Katana|Melee","Katana|Thrown Weapon","Fiber Wire","Sapper's Axe|Melee","Sapper's Axe|Thrown Weapon"],
	targetList: ["Jordan Cross","Ken Morgan"],
	contractTargets: ["Jordan Cross|Recording artist and murderer. Working on his music in the emperor suite.",
	"Ken Morgan|Power lawyer and corporate fixer. Out front of the hotel, waiting to enter his room.",
	"Dexy Barat|Cross' Manager. Heading upstairs to the recording studio in the emperor suite.",
	"Wes Liston|Music Producer. Working the mixing board upstairs in the emperor suite.",
	"Heidi Santoro|Guitarist for The Class. Playing guitar upstairs in the emperor suite.",
	"Toby Hicks|Guest residing in room 208.",
	"Jackie Carrington|Former sitcom star. Moving between the bar and room 207.",
	"Abel De Silva|Drummer auditioning for The Class. Currently at the hotel bar. (Level 2)",
	"Mrs. Mookjai|Hotel manager overseeing operations. (Level 1)",
	"Tharn Srisai|Head Chef in the hotel restaurant kitchen.",
	"Julian|Hungover “guest” of Jackie Carrington in room 207.",
	"Benjamin Bertam|Heidi Santoro’s stalker. Upstairs in the Queen Suite, across from the band.",
	"Otis Kaplan|Ken Morgan's personal bodyguard."],
	entry: ["Riverside Landing","Agent 47's Suite","Undercover in the Restaurant Kitchen","Undercover in the Linen Room","Undercover by the Security Shed","Undercover at the Himmapan Bar","Undercover in the Side Garden","Undercover in the 2nd Floor Hallway"],
	exit: ["Speedboat","Tuk-tuk|(Needs Repair)","Tunnel"],
	eexit: ["Speedboat","Tuk-tuk|(Needs Repair)","Tunnel"],
	disguises: ["Any Suit","Drummer","Exterminator","Groundskeeper","Hotel Security","Hotel Staff","Jordan Cross' Bodyguard","Kitchen Staff","Ken Morgan's Bodyguard","Recording Crew","Stalker","Waiter"],
	wild: ["The Day The Music Died|Eliminate Jordan Cross before Ken Morgan.",
	"Court Adjourned|Eliminate Ken Morgan before Jordan Cross.",
	"Keep Refrigerated|All eliminated targets must be placed in the kitchen freezer room.",
	"On the House|Escort Ken Morgan to the queen suite and clean it for him.",
	"Bugman|Have Mrs. Mookjai clear out the emperor suite for fumigation.",
	"It's My Party|Retrieve and set Jordan Cross’ birthday cake topper.",
	"Man Machine|Play the drums in front of The Class.",
	"Tik Tuk|Repair the Tuk-Tuk located behind the hotel.",
	"Keep a Souvenir|Retrieve the Branson MD-2 vocal mic.",
	"Put the Lime in the Coconut|Acquire 6 coconuts.",
	"Don't Breathe This|Pollute the ventilation system of the hotel lobby."],
	contractWild: ["Keep Refrigerated|All eliminated targets must be placed in the kitchen freezer room.",
	"Bugman|Have Mrs. Mookjai clear out the emperor suite for fumigation.",
	"Man Machine|Play the drums in front of The Class.",
	"Tik Tuk|Repair the Tuk-Tuk located behind the hotel.",
	"Keep a Souvenir|Retrieve the Branson MD-2 vocal mic.",
	"Put the Lime in the Coconut|Acquire 6 coconuts.",
	"Don't Breathe This|Pollute the ventilation system of the hotel lobby."],
};

var source = {
	missionTitle: "The Source",
	missionLocation: "Bangkok",
	missionCode: "cult",
	melee: ["Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Hatchet|Melee","Hatchet|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Katana|Melee","Katana|Thrown Weapon","Fiber Wire","Sapper's Axe|Melee","Sapper's Axe|Thrown Weapon"],
	targetList: ["Oybek Nabazov","Sister Yulduz"],
	contractTargets: ["Oybek Nabazov|Serial cult leader. Tending to his exhibit and cult members in the hotel’s queen suite.",
	"Sister Yulduz|Cult organizer. Overseeing the exhibit upstairs in the hotel’s queen suite",
	"Jeff|Currently arguing with his girlfriend in the cult exhibit bathroom.",
	"Jackie Carrington|Former sitcom star. Moving between the bar and room 207.",
	"Mrs. Mookjai|Hotel manager overseeing operations. (Level 1)",
	"Tharn Srisai|Head Chef in the hotel restaurant kitchen.",
	"Julian|Hungover “guest” of Jackie Carrington in room 207."],
	entry: ["Hotel Front Terrace"],
	exit: ["Speedboat","Tunnel"],
	eexit: ["Speedboat","Tunnel"],
	disguises: ["Any Suit","Exterminator","Groundskeeper","Hotel Security","Hotel Staff","Cult Bodyguard","Kitchen Staff","Waiter","Cult Member"],
	wild: ["Spilled Flavor Crystals|Eliminate Oybek Nabazov before Sister Yulduz.",
	"Disorganized|Eliminate Sister Yulduz before Oybek Nabazov.",
	"Something For Later|Find and collect the 92 Proof Vodka. Do not use it during the contract.",
	"Inner Circle|Attend the private ceremony as a cult member."],
	contractWild: ["Something For Later|Find and collect the 92 Proof Vodka. Do not use it during the contract.",
	"Inner Circle|Attend the private ceremony as a cult member."],
};

var ff = {
	missionTitle: "Freedom Fighters",
	missionLocation: "Colorado",
	missionCode: "terrorists",
	melee: ["Cleaver|Melee","Cleaver|Thrown Weapon","Old Axe|Melee","Old Axe|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fiber Wire"],
	targetList: ["Sean Rose","Penelope Graves","Ezra Berg","Maya Parvati"],
	contractTargets: ["Sean Rose|Radical activist and bomb maker. Moving between the farmhouse and the bomb testing site.",
	"Penelope Graves|Former Interpol anti-terror analyst. Roaming the compound, mainly the garden.",
	"Ezra Berg|Retired Mossad agent. Interrogating a man in the farmhouse basement.",
	"Maya Parvati|Training instructor and former assassin. Working with recruits in the barn.",
	"Quince Elliot|Explosives specialist. Working between the canopy and the bomb test range.",
	"Robert Powell|Militia cook. Cooking at the stove in the garden area.",
	"Lloyd Burgess|Injured Point Man resting in the southern bunks.",
	"Milton Geiger|Militia technician working on a car in the garage.",
	"Mario Thompson|Militia soldier sleeping on a couch in the buildings to the east.",
	"Liam Butler|Militia spec ops. Checking on equipment in the barn.",
	"Albert Knarr|Drill instructor occasionally drilling soldiers in the farmhouse backyard.",
	"Raymond Kane|Militia technician working on the taco van outside the garage.",
	"Scott Harris|Militia soldier on the roof of the mechanic’s garage.",
	"Terry Ehrhart|Relative of the former compound owner. At the grave next to the farmhouse.",
	"Andre Washington|Militia elite patrolling the upstairs of the farmhouse.",
	"Reese Faulkner|Militia elite guarding Sean Rose’s room in the farmhouse.",
	"Aaron Collier|Militia soldier using binoculars on the roof of the bunks in the south."],
	entry: ["Undercover in the Garage","West Bridge","Undercover by the Greenhouse","Undercover on the Demolition Range","Old Orchard","Southern Farm Perimeter","Undercover in the Farmhouse","Water Tower"],
	exit: ["Bridge","Quad Bike|(Needs Key)","River","Front Gate","Tornado Shelter|(Needs Face Scan)"],
	eexit: ["Bridge","Quad Bike|(Needs Key)","River","Front Gate","Tornado Shelter|(Needs Face Scan)","Mr. Raptor|(Secret)"],
	disguises: ["Any Suit","Explosives Specialist","Hacker","Militia Cook","Militia Elite","Militia Spec Ops","Militia Soldier","Militia Technician","Point Man","Scarecrow"],
	wild: ["Blow Up His Spot|Eliminate Sean Rose before all other targets.",
	"Spill Your Guts|Eliminate Ezra Berg before all other targets.",
	"Lead by Example|Eliminate Maya Parvati before all other targets.",
	"Analyze This|Eliminate Penelope Graves before all other targets.",
	"Fizzle Out|Eliminate Sean Rose after eliminating all other targets.",
	"Tight-lipped|Eliminate Ezra Berg after eliminating all other targets.",
	"Fail Your Training|Eliminate Maya Parvati after eliminating all other targets.",
	"Fudged The Numbers|Eliminate Penelope Graves after eliminating all other targets.",
	"Compound Keys|Find all 4 keys scattered around: Basement Key, Garage Key, Perimeter Gate Key, and Rose's Room Key.",
	"Better Safe Than Sorry|Find and collect both the hacker’s phone and the explosive watch battery.",
	"The Good Stuff|Find and collect the hallucinogenic drugs.",
	"Perfect Forgery|Find and collect the interpol badge.",
	"Handle With Care|Acquire 5 bottles of Nitroglycerin.",
	"Not Exactly Ulcer Pills|Play the video game console.",
	"Apricot Hunter|Find and collect 10 apricots.",
	"Apricot Hoarder|Find and collect 20 apricots."],
	contractWild: ["Compound Keys|Find all 4 keys scattered around: Basement Key, Garage Key, Perimeter Gate Key, and Rose's Room Key.",
	"Better Safe Than Sorry|Find and collect both the hacker’s phone and the explosive watch battery.",
	"The Good Stuff|Find and collect the hallucinogenic drugs.",
	"Perfect Forgery|Find and collect the interpol badge.",
	"Handle With Care|Acquire 5 bottles of Nitroglycerin.",
	"Not Exactly Ulcer Pills|Play the video game console.",
	"Apricot Hunter|Find and collect 10 apricots.",
	"Apricot Hoarder|Find and collect 20 apricots."],
};

var si = {
	missionTitle: "Situs Inversus",
	missionLocation: "Hokkaido",
	missionCode: "heart",
	melee: ["Fiber Wire","Scalpel|Melee","Scalpel|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Katana|Melee","Katana|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon"],
	targetList: ["Erich Soders","Yuki Yamazaki"],
	contractTargets: ["Yuki Yamazaki|Cutthroat Yakuza lawyer. Roaming between GAMA’s luxury areas and her room.",
	"Lowell Aucoin|Resort staff showering in the staff area near the lockers.",
	"Eric 'Sandā no ashi' Sjövold|Handyman playing a dancing video game against another player.",
	"Amos Dexter|Stetson patient awaiting lung transplant. Smokes in his room while not wandering.",
	"Akira Nakamura|Director of GAMA. Making rounds of the guest area and outdoor garden.",
	"Jason Portman|Plastic surgery patient in the guest area awaiting a call for a checkup.",
	"J. Brooke|Injured yoga instructor. Limping between the loading bay and hot springs.",
	"Nicholas Laurent|Head surgeon of GAMA. Looking for a ‘fix’ from Nails, the helicopter pilot.",
	"Nails|Helicopter pilot for GAMA. Supplies drugs to the head surgeon for his trembling hands.",
	"Hanna Olsen|Nurse in the operating theater, namely the stem cell controls.",
	"Katashi Ito|Head of GAMA’s morgue. A microchip in his brain can control his mood.",
	"Tomiyuki Fujihara|Handyman working nearby the helipad, trying to have a smoke in private.",
	"Azuma Murayama|Handyman in the staff hallway under the guest area, next to the lake window.",
	"Carlton Smith|Interpol agent MIA after investigating an illegal organ harvesting operation in GAMA."],
	entry: ["Tobias Rieper's Suite","Spa","Infiltrating Along the Mountain Path","Restaurant","Undercover in the Staff Quarters","Undercover in the Kitchen","Undercover in the Garden","Morgue","Undercover in the Operating Theater"],
	exit: ["Helicopter","Snowmobile","Hiking Route","Cable Car"],
	eexit: ["Helicopter","Snowmobile","Hiking Route","Cable Car"],
	sodersKills: ["Trash the Donor Heart|Target Specific","Shoot the Donor Heart|Target Specific","Overcharge Defibrillator|Target Specific","Pistol","Large Firearm","Explosion","Poison the Stem Cells|Target Specific","Reveal Yourself as 47|Target Specific","Fail the Surgery|Target Specific","Surgeon Commits Murder|Target Specific","Robot Arms|Target Specific"],
	disguises: ["Any Suit / Ninja","Baseball Player","Bodyguard","Chef","Chief Surgeon","Doctor","Handyman","Helicopter Pilot","Hospital Director","Morgue Doctor","Motorcyclist","Patient","Resort Security","Resort Staff","Surgeon","VIP Patient (Dexter)","VIP Patient (Portman)","Yoga Instructor"],
	wild: ["Disbarred|Eliminate Yuki Yamazaki before Erich Soders.",
	"You're Fired|Eliminate Erich Soders before Yuki Yamazaki.",
	"Ghost in the Machine|Sabotage GAMA’s artificial intelligence mainframe KAI.",
	"Namaste|Change the temperatures of both the hot spring and sauna, trigger the fire alarm, then wait for the guests to meditate.",
	"Mood Alteration|Find and collect the neurochip remote.",
	"Smell Something Fishy?|Cut the fugu fish to collect it’s poison.",
	"Guardian Angel|Both initiate and prevent Katashi Ito from killing himself using only the neurochip remote.",
	"ICA Records|Find and collect Erich Soders' kill list flash drive.",
	"All Access Pass|Find and collect the RFID master chip card.",
	"Smoking Kills|Find and collect 3 packs of cigarettes.<br />Note: you will need to keep track of the amount on your own.",
	"New Career Path|Prepare and serve 3 different people unpoisoned sushi."],
	contractWild: ["Ghost in the Machine|Sabotage GAMA’s artificial intelligence mainframe KAI.",
	"Namaste|Change the temperatures of both the hot spring and sauna, trigger the fire alarm, then wait for the guests to meditate.",
	"Mood Alteration|Find and collect the neurochip remote.",
	"Smell Something Fishy?|Cut the fugu fish to collect it’s poison.",
	"Guardian Angel|Both initiate and prevent Katashi Ito from killing himself using only the neurochip remote.",
	"All Access Pass|Find and collect the RFID master chip card.",
	"Smoking Kills|Find and collect 3 packs of cigarettes.<br />Note: you will need to keep track of the amount on your own.",
	"New Career Path|Prepare and serve 3 different people unpoisoned sushi."],
};

var patientzero = {
	missionTitle: "Patient Zero",
	missionLocation: "Hokkaido",
	missionCode: "spread",
	melee: ["Fiber Wire","Scalpel|Melee","Scalpel|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Katana|Melee","Katana|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon"],
	targetList: ["Owen Cage","Klaus Liebleid"],
	contractTargets: ["Owen Cage|Patient Zero. About to be lead into the operating theater for examination.",
	"Klaus Liebleid|Ether’s best researcher. Examining Owen Cage to reverse engineer the virus."],
	entry: ["Infiltrating below the Helipad"],
	exit: ["Snowmobile","Hiking Route","Cable Car"],
	eexit: ["Snowmobile","Hiking Route","Cable Car"],
	disguises: ["Undercover Gear","Head Researcher (Klaus)","Bio Suit","Bodyguard","Chef","Chief Surgeon","Doctor","Handyman","Helicopter Pilot","Hospital Director","Morgue Doctor","Motorcyclist","Patient","Resort Security","Resort Staff","Surgeon","VIP Patient (Dexter)","Yoga Instructor"],
	wild: ["Lucky Shot|Become infected with the Nabazov Virus, but cure it with 10 seconds or less remaining until 47's death.", 
	"You Know the Number|Kill at least 47 people infected with the Nabazov Virus besides Owen Cage.",
	"Containment|Complete the mission with no one else being infected by the Nabazov Virus.",
	"Namaste|Change the temperatures of both the hot spring and sauna, trigger the fire alarm, then wait for the guests to meditate.",
	"Smell Something Fishy?|Cut the fugu fish to collect it’s poison."],
	contractWild: ["Lucky Shot|Become infected with the Nabazov Virus, but cure it with 10 seconds or less remaining until 47's death.", 
	"You Know the Number|Kill at least 47 people infected with the Nabazov Virus besides Owen Cage.",
	"Containment|Complete the mission with no one being infected by Nabazov Virus.",
	"Namaste|Change the temperatures of both the hot spring and sauna, trigger the fire alarm, then wait for the guests to meditate.",
	"Smell Something Fishy?|Cut the fugu fish to collect it’s poison."]
};

var nc = {
	missionTitle: "Nightcall",
	missionLocation: "Hawke's Bay",
	missionCode: "beach",
	melee: ["Fiber Wire"],
	targetList: ["Alma Reynard"],
	contractTargets: ["Alma Reynard|TBD"],
	entry: ["Boat","Beach","Office"],
	exit: ["Boat|(Needs Destraction)"],
	eexit: ["Boat|(Needs Destraction)"],
	disguises: ["Any Suit","Bodyguard"],
	wild: ["Total Elimination|Kill everyone in the level only after taking out Alma Reynard.<br /><br />If killing non-targets is not permitted, then only pacify.",
	"Under The Mat|Find and collect the hidden house key.",
	"Don't Tread On Me!|Find and collect two squeaky toys.",
	"Wood You Believe It?|Find and collect two pieces of driftwood."],
	contractWild: ["Total Elimination|Kill everyone in the level only after taking out the target(s).<br /><br />If killing non-targets is not permitted, then only pacify.",
	"Under The Mat|Find and collect the hidden house key.",
	"Don't Tread On Me!|Find and collect two squeaky toys.",
	"Wood You Believe It?|Find and collect two pieces of driftwood."]
};

var tfl = {
	missionTitle: "The Finish Line",
	missionLocation: "Miami",
	missionCode: "speedway",
	melee: ["Fiber Wire","Amputation Knife|Melee","Amputation Knife|Thrown Weapon","Battle Axe|Melee","Battle Axe|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Starfish","Fire Axe|Melee","Fire Axe|Thrown Weapon","Old Axe|Melee","Old Axe|Thrown Weapon"],
	targetList: ["Sierra Knox","Robert Knox"],
	contractTargets: ["Sierra Knox|TBD","Robert Knox|TBD"],
	entry: ["Event Entrance","Dolphin Fountain","Marina","Stands","Food Stand","Overpass","Driver's Lounge","Podium","Medical Area","Kronstadt Bayside Center","Kowoon Pit"],
	exit: ["Helicopter", "Main Entrance","Sewer|(Needs Crowbar)","Speedboat|(Needs Key)","Ambulance|(Medic Only)"],
	eexit: ["Helicopter", "Main Entrance","Sewer|(Needs Crowbar)","Speedboat|(Needs Key)","Ambulance|(Medic Only)","Nest|(Secret)","Dolphin Statue|(Secret)","Pale Rider|(Secret)"],
	disguises: ["Any Suit","Aeon Driver","Aeon Mechanic","Event Crew","Event Security","Florida Man","Food Vendor","Journalist","Kitchen Staff","Kowoon Driver","Kowoon Mechanic","Kronstadt Engineer","Kronstadt Researcher","Kronstadt Security","Mascot","Medic","Moses Lee","Pale Rider","Photographer","Race Coordinator","Race Marshall","Sheik","Sotteraneo Mechanic","Street Musician","Ted Mendez","Thwack Driver","Waiter","Blue Seed Driver","Kronstadt Driver","Kronstadt Mechanic"],
	wild: ["Burst The Bubble|Eliminate Robert Knox before Sierra Knox.",
	"Last Lap|Eliminate Sierra Knox before Robert Knox.",
	"Bring a Tear To His Eye|Ensure Robert Knox takes his eye drops.",
	"One Kilo Brick|Get a brick of cocaine.",
	"Frutti Di Mare|Find the two aquatic weapons within Miami.",
	"Sweet Tooth|Find and collect 4 Bags of Sugar.",
	"What's In This Thing|Open and collect the contents of the evidence locker.",
	"Blackmail|Find and collect the blackmail documents.",
	"Communications Breakdown|Sabotage the satellite dish.",
	"Tintamarresque|Blend in using the photo stand-in.",
	"Free Fishie|Release a fish back into the ocean.",
	"Tanked|Knock out both aquarium guards at the same time using the same aquarium.",
	"Potty Training|Make the patient leave the doctor's office without eliminating him."],
	contractWild: ["One Kilo Brick|Get a brick of cocaine.",
	"Frutti Di Mare|Find the two aquatic weapons within Miami.",
	"Sweet Tooth|Find and collect 4 Bags of Sugar.",
	"What's In This Thing|Open and collect the contents of the evidence locker.",
	"Blackmail|Find and collect the blackmail documents.",
	"Communications Breakdown|Sabotage the satellite dish.",
	"Tintamarresque|Blend in using the photo stand-in.",
	"Free Fishie|Release a fish back into the ocean.",
	"Tanked|Knock out both aquarium guards at the same time using the same aquarium.",
	"Potty Training|Make the patient leave the doctor's office without eliminating him."]
};

var ths = {
	missionTitle: "Three-headed Serpent",
	missionLocation: "Columbia",
	missionCode: "cartel",
	melee: ["Fiber Wire","Screwdriver|Melee","Screwdriver|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Barber Razor|Melee","Barber Razor|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Machete|Melee","Machete|Thrown Weapon"],
	targetList: ["Rico Delgado","Jorge Franco","Andrea Martinez"],
	contractTargets: ["Rico Delgado|TBD","Jorge Franco|TBD","Andrea Martinez|TBD"],
	entry: ["Village Bus Stop","Village Hostel","Shaman's Hut","Village Bar","Construction Site","Coca Fields","Submarine Cave","Mansions Basement"],
	exit: ["Rico's Supercar|(Needs Key)","Helicopter","Speedboat|(Needs Key)","Local's Car|(Needs Key)","Scooter|(Needs Key)","Boat","Village Bus Stop"],
	eexit: ["Rico's Supercar|(Needs Key)","Helicopter","Speedboat|(Needs Key)","Local's Car|(Needs Key)","Scooter|(Needs Key)","Boat","Village Bus Stop"],
	disguises: ["Any Suit","Drummer","Hippo Whisperer","Shaman","Submarine Crew","Submarine Engineer","Tattoo Artist","Coca Field Worker","Construction Worker","Mansion Staff","Mansion Guard","Coca Field Guard","Elite Guard","Street Soldier","Hippie","Barman","Gardener","Chef"],
	wild: ["Being Thorough|Eliminate Rico Delgato before all other targets.",
	"Forgotten Recipe|Eliminate Jorge Franco before all other targets.",
	"Run Into The Ground|Eliminate Andrea Martinez before all other targets.",
	"Secret Tunnel|Shamen. Idol. Open. Path. Knife.",
	"Cog In The Machine|Recover Franco's missing circuit board.",
	"Feedin' Time|Make the hippo feel better.",
	"Don't Shoot The Messenger|Find Héctor Delgado's love letter.",
	"Salt The Earth|Destroy Franco's rare flower sample.",
	"How Ribbiting|Catch 5 frogs."],
	contractWild: ["Secret Tunnel|Shamen. Idol. Open. Path. Knife.",
	"Cog In The Machine|Recover Franco's missing circuit board.",
	"Feedin' Time|Make the hippo feel better.",
	"Don't Shoot The Messenger|Find Héctor Delgado's love letter.",
	"Salt The Earth|Destroy Franco's rare flower sample.",
	"How Ribbiting|Catch 5 frogs."]
};

var cag = {
	missionTitle: "Chasing a Ghost",
	missionLocation: "Mumbai",
	missionCode: "ghost",
	melee: ["Fiber Wire","Beak Axe|Melee","Beak Axe|Thrown Weapon","Old Axe|Melee","Old Axe|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Measuring Tape","Amputation Knife|Melee","Amputation Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Barber Razor|Melee","Barber Razor|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Folding Knife|Melee","Folding Knife|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Saber|Melee","Saber|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon"],
	targetList: ["The Maelstrom","Vanya Shah","Dawood Rangan"],
	contractTargets: ["The Maelstrom|TBD","Vanya Shah|TBD","Dawood Rangan|TBD"],
	entry: ["Main Street","Train","Boat","Skywalk","Taxi","Chawls","Laundry","Barge","Slums","Metal Forge","Photo Shoot","Hill","Train Yard"],
	exit: ["Boat","Main Street","Main Street North","Taxi|(Pay 1-2 Coins)","Train|(Needs Lever)","Crows Nest Tunnel|(Needs Key)"],
	eexit: ["Boat","Main Street","Main Street North","Taxi|(Pay 1-2 Coins)","Train|(Needs Lever)","Crows Nest Tunnel|(Needs Key)"],
	disguises: ["Any Suit","Local Security","Food Vendor","Thug","Elite Thug","Metal Worker","Tailor","Queen's Guard","Vanya's Servant","Queen's Bodyguard","Laundry Worker","Laundry Foreman","Dancer","Holy Man","Lead Actor","Kashmirian","Barber","Bollywood Crew","Bollywood Bodyguard","Painter"],
	wild: ["Legend Lost|Find and eliminate The Maelstrom before all other targets.",
	"That's A Wrap|Eliminate Dawood Rangan before all other targets.",
	"Long Live the Queen|Eliminate Vanya Shah before all other targets.",
	"A Secret Grudge|Find and read Vanya Shah's diary.",
	"A Dark Scheme|Investigate Dawood Rangan's private laptop.",
	"Not in the Script|Find the missing manuscript in Rangan Tower.",
	"The Artist|Allow the artist to finish his painting of Dawood Rangan... uninterrupted.",
	"Memoir|Find one tape recorded by The Maelstrom.",
	"Big Spender|Buy all three cloth samples from a vendor in the slums."],
	contractWild: ["A Secret Grudge|Find and read Vanya Shah's diary.",
	"A Dark Scheme|Investigate Dawood Rangan's private laptop.",
	"Not in the Script|Find the missing manuscript in Rangan Tower.",
	"The Artist|Allow the artist to finish his painting of Dawood Rangan.",
	"Memoir|Find one tape recorded by The Maelstrom",
	"Smashing, Baby!|Start the photoshoot as the lead actor.",
	"Big Spender|Buy all three cloth samples from a vendor in the slums."]
};

var al = {
	missionTitle: "Another Life",
	missionLocation: "Whittleton Creek",
	missionCode: "suburbs",
	melee: ["Fiber Wire","Old Axe|Melee","Old Axe|Thrown Weapon","Kitchen Knife|Melee","Kitchen Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Scissors|Melee","Scissors|Thrown Weapon","Letter Opener|Melee","Letter Opener|Thrown Weapon","Fire Axe|Melee","Fire Axe|Thrown Weapon","Hatchet|Melee","Hatchet|Thrown Weapon"],
	targetList: ["Janus","Nolan Cassidy"],
	contractTargets: ["Janus|TBD","Nolan Cassidy|TBD"],
	entry: ["Whittleton Creek","Construction Area","Fumigation","Garbage Removal","Suburb Sign","BBQ Party"],
	exit: ["Bus Stop","Bridge","Raft|(Needs Paddle)","Sewer|(Needs Crowbar)","Construction Van|(Needs Key)","Trash Truck|(Garbage Man Only)","Roadwork Gate|(Needs Key)"],
	eexit: ["Bus Stop","Bridge","Raft|(Needs Paddle)","Sewer|(Needs Crowbar)","Construction Van|(Needs Key)","Trash Truck|(Garbage Man Only)","Roadwork Gate|(Needs Key)"],
	disguises: ["Any Suit","Exterminator","Politician","Real Estate Broker","Nurse","Arkian Robe","Janus' Bodyguard","Cassidy Bodyguard","Police Debuty","Construction Crew","Politician's Assistant","Server","Garbage Man","Spencer 'The Hammer' Green","BBQ Owner","Mailman","Gunther Mueller","Gardener","James Batty","Plumber"],
	wild: ["Forget The Past|Eliminate Janus before Nolan Cassidy.",
	"Changing Of The Guard|Eliminate Nolan Cassidy before Janus.",
	"Battle Frogs|Capture a pickerel frog.",
	"Junk Mail|Aquire the package meant for Mr. Batty, but deliver him a political flyer instead.",
	"Old Grudges|Unearth and take the hatchet.",
	"Bake Sale|Aquire 10 blueberry muffins."],
	contractWild: ["Battle Frogs|Capture a pickerel frog.",
	"Junk Mail|Aquire the package meant for Mr. Batty, but deliver him a political flyer instead.",
	"Old Grudges|Unearth and take the hatchet.",
	"Bake Sale|Aquire 10 blueberry muffins."]
};

var tas = {
	missionTitle: "The Ark Society",
	missionLocation: "Isle of Sgàil",
	missionCode: "ark",
	melee: ["Fiber Wire","Battle Axe|Melee","Battle Axe|Thrown Weapon","Broadsword","Saber|Melee","Saber|Thrown Weapon","Old Axe|Melee","Old Axe|Thrown Weapon","Katana|Melee","Katana|Thrown Weapon","Burial Dagger|Melee","Burial Dagger|Thrown Weapon","Circumcision Knife|Melee","Circumcision Knife|Thrown Weapon","Screwdriver|Melee","Screwdriver|Thrown Weapon","Sapper's Axe|Melee","Sapper's Axe|Thrown Weapon","Cleaver|Melee","Cleaver|Thrown Weapon","Scalpel|Melee","Scalpel|Thrown Weapon","Hatchet|Melee","Hatchet|Thrown Weapon","Viking Axe|Melee","Viking Axe|Thrown Weapon","Aztec Necklace","Scissors|Melee","Scissors|Thrown Weapon"],
	targetList: ["Zoe Washington","Sophia Washington"],
	contractTargets: ["Zoe Washington|TBD","Sophia Washington|TBD"],
	entry: ["Harbor","Chapel","Keep","Reception Area","Kitchens","Warehouse","Gallery","Architects' Lounge"],
	exit: ["Speedboat","Helipad","East Wall","Rooftop|(Needs Flare)","Warehouse Ladder"],
	eexit: ["Speedboat","Helipad","East Wall","Rooftop|(Needs Hand Flare)","Warehouse Ladder","Swan Dive|(Secret)"],
	disguises: ["Any Suit","Initiate","Ark Member","Architect","Jebediah Block","Burial Robes","Knight","Event Staff","Chef","Custodian","Raider","Elite Guard","Musician","Blake Nathaniel","Entertainer","Butler","Castle Staff","Master of Ceremonies"],
	wild: ["People Person|Eliminate Zoe Washington before Sophia Washington.",
	"Plan Accordingly|Eliminate Sophia Washington before Zoe Washington.",
	"Five Finger Discount|Steal the Astek necklace."],
	contractWild: ["Five Finger Discount|Steal the Astek necklace."]
};

var mission_names_map = {
	"FFT" : fft,
	"TFT" : ica,
	"TSS" : showstopper,
	"WOT": wot,
	"ICON": icon,
	"LS": landslide,
	"TA": author,
	"AGC": agc,
	"AHBOS": ahbos,
	"C27": c27,
	"TS": source,
	"FF": ff,
	"SI": si,
	"PZ": patientzero,
	"NC": nc,
	"TFL": tfl,
	"THS": ths,
	"CAG": cag,
	"AL": al,
	"TAS": tas
}

var killTypesMap = {
	"melee": "melee",
	"firearm": "firearms",
	"accident": "accidents",
	"generic": "kills"
}